[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "django_business_metrics"
version = "0.1.0"
description = "Django Prometheus business metrics"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "BSD 3-Clause License"}
dependencies = [
    "Django",
    "prometheus_client",
]